

######################## Target All ########################

### get all providers 
GET http://localHost:8080/api/providers

###################### Target Specific #####################

### get a specific provider
GET http://localHost:8080/api/providers/specific/5ffb559cd5000b13c432796a

### add an delivery city
POST http://localHost:8080/api/providers/specific/5ffb559cd5000b13c432796a
content-type: application/json

{
    "deliveryCities": ["Tel-Aviv", "Rehovot", "Rishon Lezion"]
}

### delete specific provider
DELETE http://localHost:8080/api/providers/specific/6002e43b0d0f3b00d897f5c7

########################## Other ###########################

### sign-up a providers
POST http://localHost:8080/api/providers/sign-up HTTP/1.1
content-type: application/json

{
    "userEmail": "company@example.com",
    "userPassword": "company",
    "userFirstName": "companyito", 
    "userLastName": "companosh", 
    "userPhoneNumber": "054-555-5555", 
    "userAddresses": [{
        "name": "Store",
        "city": "testavile",
        "street": "testastreet",
        "houseNumber": "3"
    }],
    "businessName": "Biz Biz",
    "businessWebsite": "https://www.test.com/"
}