

######################## Target All ########################

### get all users 
GET http://localHost:8080/api/users

###################### Target Specific #####################

### get specific user
GET http://localHost:8080/api/users?id=5fd3d0bbccb74d3b1c307e64

### add an address
PATCH http://localHost:8080/api/users/5fd3d0bbccb74d3b1c307e64
content-type: application/json

{
    "addresses": [{
        "name": "Home",
        "city": "testavile",
        "street": "testastreet",
        "houseNumber": "4/5",
        "floorNumber": "7",
        "aptNumber": "7"
    }]
}

### delete specific user
DELETE http://localHost:8080/api/users/5fd3d0bbccb74d3b1c307e64

########################## Other ###########################

### register a user
POST http://localHost:8080/api/users/signup HTTP/1.1
content-type: application/json

{
    "emailAddress":"test@gmail.com",
    "password":"testtest",
    "firstName":"Test",
    "surName":"Testush",
    "phoneNumber":"050-546-6646"
}

### sign in a user
POST http://localHost:8080/api/users/signin HTTP/1.1
content-type: application/json

{
    "emailAddress":"test@gmail.com",
    "password":"testtest"
}