

######################## Target All ########################

### get all users 
GET http://localHost:8080/api/users

###################### Target Specific #####################

### get a specific user
GET http://localHost:8080/api/users/specific/5ffb524ab4a57a47f424ed47

### add an address
POST http://localHost:8080/api/users/specific/5ffb524ab4a57a47f424ed47
content-type: application/json

{
    "userAddresses": [{
        "name": "temp",
        "city": "tempavile",
        "street": "tempastreet",
        "houseNumber": "2"
    }]
}

### delete specific user
DELETE http://localHost:8080/api/users/specific/5ffb524ab4a57a47f424ed47

########################## Other ###########################

### sign-in
POST http://localHost:8080/api/users/sign-in HTTP/1.1
content-type: application/json

{
    "userEmail": "test@example.com",
    "userPassword": "tes67t123"
}

### sign-up
POST http://localHost:8080/api/users/sign-up HTTP/1.1
content-type: application/json

{
    "userEmail": "test@example.com",
    "userPassword": "test123",
    "userFirstName": "testito", 
    "userLastName": "testosh", 
    "userPhoneNumber": "054-555-5555", 
    "userAddress": {
        "name": "Home",
        "city": "testavile",
        "street": "testastreet",
        "houseNumber": "4/5",
        "floorNumber": "7",
        "aptNumber": "7"
    }
}