
const Flowers = {
    1:{
        _id:1,
        type:'ALSTROEMERIA',
        color:'PINK',
        productDescription:"Test",
        productImage:"https://www.countryfarmperennials.com.au/wp-content/uploads/2018/09/ALSTROEMERIA-APPEL-BLOESEM-SMALL-.jpg"
    },
    2:{
        _id:2,
        type:'ALSTROEMERIA',
        color:'WHITE',
        productDescription:"Test2",
        productImage:"https://helonational.com/wp-content/uploads/2016/03/National-flower-of-italy.jpg"
    },
    3:{
        _id:3,
        type:'ALSTROEMERIA',
        color:'PURPLE',
        productDescription:"Test3",
        productImage:"https://static.onecms.io/wp-content/uploads/sites/37/2020/06/17/purple-white-alstroemeria-1bbc41b6.jpg"
    },
    4:{
        _id:4,
        type:'ROSE',
        color:'PINK',
        productDescription:"Test32",
        productImage:"https://img.crocdn.co.uk/images/products2/pl/20/00/01/76/pl2000017678.jpg?width=440&height=440"
    },
    5:{
        _id:5,
        type:'ROSE',
        color:'WHITE',
        productDescription:"Test4",
        productImage:"https://www.almanac.com/sites/default/files/image_nodes/rose-peach.jpg"
    },
    6:{
        _id:6,
        type:'ROSE',
        color:'BLACK',
        productDescription:"Test5",
        productImage:"https://helonational.com/wp-content/uploads/2016/03/National-flower-of-italy.jpg"
    },
    7:{
        _id:7,
        type:'ROSE',
        color:'RED',
        productDescription:"Test6",
        productImage:"https://www.jacksonandperkins.com/images/xxl/v1780.jpg"
    },
    8:{
        _id:8,
        type:'LILY',
        color:'WHITE',
        productDescription:"Test7",
        productImage:"https://helonational.com/wp-content/uploads/2016/03/National-flower-of-italy.jpg"
    },
    9:{
        _id:9,
        type:'LILY',
        color:'WHITE',
        productDescription:"Test8",
        productImage:"https://helonational.com/wp-content/uploads/2016/03/National-flower-of-italy.jpg"
    },
    10:{
        _id:10,
        type:'LILY',
        color:'PINK',
        productDescription:"Test9",
        productImage:"https://helonational.com/wp-content/uploads/2016/03/National-flower-of-italy.jpg"
    },
    11:{
        _id:11,
        type:'LILY',
        color:'YELLOW',
        productDescription:"Test10",
        productImage:"https://helonational.com/wp-content/uploads/2016/03/National-flower-of-italy.jpg"

    },
}

export default Flowers;