const orders = [
    {
        userID: "_1",
        Address:  {
            name: "home",
            city: "Tel Aviv",
            street: "Prague",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/02/2021",
        nextShippingDate: "01/02/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 100,
        flowerBouquetIds: ["test"],
    },
    {
        userID: "_2",
        Address:  {
            name: "grandma",
            city: "Tel Aviv",
            street: "dizingof",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/03/2021",
        nextShippingDate: "01/03/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 200,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_3",
        Address:  {
            name: "office",
            city: "Ramat Gan",
            street: "herztel",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "13/02/2021",
        nextShippingDate: "20/02/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 200,
        flowerBouquetIds: ["test"],
    },
    {
        userID: "_4",
        Address:  {
            name: "home",
            city: "Tel Aviv",
            street: "Prague",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/02/2021",
        nextShippingDate: "01/02/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 100,
        flowerBouquetIds: ["test"],
    },
    {
        userID: "_5",
        Address:  {
            name: "home",
            city: "Ramat Gan",
            street: "abc",
            houseNumber: "10",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/11/2021",
        nextShippingDate: "01/11/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 150,
        flowerBouquetIds: ["test"],
    },
    {
        userID: "_6",
        Address:  {
            name: "home",
            city: "Tel Aviv",
            street: "Prague",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/01/2021",
        nextShippingDate: "01/02/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 150,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_7",
        Address:  {
            name: "home",
            city: "Givataym",
            street: "Prague",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/09/2021",
        nextShippingDate: "01/09/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 150,
        flowerBouquetIds: ["test"],
    },
    {
        userID: "_8",
        Address:  {
            name: "home",
            city: "Givataym",
            street: "Rotschild",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "7",
        },
        frequencyWeeks: "1",
        startDate: "01/09/2021",
        nextShippingDate: "01/09/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 150,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_9",
        Address:  {
            name: "home",
            city: "Ramat Sharon",
            street: "Prague",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/09/2021",
        nextShippingDate: "01/09/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 150,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_10",
        Address:  {
            name: "home",
            city: "Rishon Leztion",
            street: "Rotchild",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "2",
        startDate: "02/09/2021",
        nextShippingDate: "01/10/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 150,
        flowerBouquetIds: ["test"],
    },


    {
        userID: "_11",
        Address:  {
            name: "home",
            city: "Hod HaSharon",
            street: "hertzel",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "07/09/2021",
        nextShippingDate: "01/10/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 150,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_12",
        Address:  {
            name: "home",
            city: "Rehovot",
            street: "Prague",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/09/2021",
        nextShippingDate: "01/09/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 150,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_13",
        Address:  {
            name: "home",
            city: "Ramat Sharon",
            street: "Macabi",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/09/2021",
        nextShippingDate: "01/11/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 150,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_14",
        Address:  {
            name: "home",
            city: "Ness Ziona",
            street: "Lotus",
            houseNumber: "11",
            floorNumber: "-",
            aptNumber: "-",
        },
        frequencyWeeks: "2",
        startDate: "01/09/2021",
        nextShippingDate: "01/11/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 150,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_15",
        Address:  {
            name: "home",
            city: "Rehovot",
            street: "Hertzel",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/12/2021",
        nextShippingDate: "01/12/2021",
        orderCategory: "NUTS",
        active: true,
        totalSum: 300,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_16",
        Address:  {
            name: "office",
            city: "Rehovot",
            street: "Weizmann",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/12/2021",
        nextShippingDate: "01/12/2021",
        orderCategory: "NUTS",
        active: true,
        totalSum: 400,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_17",
        Address:  {
            name: "mom",
            city: "Ramat Sharon",
            street: "Sayfan",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/12/2021",
        nextShippingDate: "01/12/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 400,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_18",
        Address:  {
            name: "bff",
            city: "Ramat Sharon",
            street: "Lotus",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/12/2021",
        nextShippingDate: "01/12/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 400,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_19",
        Address:  {
            name: "Family",
            city: "Ramat Sharon",
            street: "Sayfan",
            houseNumber: "11",
            floorNumber: "4",
            aptNumber: "6",
        },
        frequencyWeeks: "2",
        startDate: "01/12/2021",
        nextShippingDate: "01/12/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 400,
        flowerBouquetIds: ["test"],
    },

    {
        userID: "_20",
        Address:  {
            name: "mom",
            city: "Tel Aviv",
            street: "Sayfan",
            houseNumber: "11",
            floorNumber: "3",
            aptNumber: "6",
        },
        frequencyWeeks: "1",
        startDate: "01/12/2021",
        nextShippingDate: "01/12/2021",
        orderCategory: "BOUQUET",
        active: true,
        totalSum: 400,
        flowerBouquetIds: ["test"],
    },

]