const Users = [
    { 
        _id=1,
        emailAddress:"Guy.nudelman@aol.com",
        userRole:'ADMIN',
        firstName:"Guy",
        surName:"Nudelman",
        phoneNumber:"054-3399-082",
        addresses:[{
                name:"Home",
                city:"Netaim",
                street:"Hail",
                houseNumber:"3",
                floorNumber:0,
                aptNumber:0
            }],
        cart:[{
            orders:["test"],
            totalSum:100
        }]
    },
    { 
        _id=2,
        emailAddress:"Guy.TEST@aol.com",
        userRole:'USER',
        firstName:"Test1",
        surName:"Test1",
        phoneNumber:"054-5646-082",
        addresses:[{
                name:"Home",
                city:"Tel-Aviv",
                street:"Hail",
                houseNumber:"3",
                floorNumber:0,
                aptNumber:0
            }],
        cart:[{
            orders:["test"],
            totalSum:200
        }]
    },
    { 
        _id=3,
        emailAddress:"Guy.TEST2@aol.com",
        userRole:'USER',
        firstName:"Test2",
        surName:"Test2",
        phoneNumber:"054-3451-082",
        addresses:[{
                name:"Home",
                city:"Rishon",
                street:"Hail",
                houseNumber:"3",
                floorNumber:2,
                aptNumber:0
            }],
        cart:[{
            orders:["test"],
            totalSum:150
        }]
    },  
    { 
        _id=4,
        emailAddress:"Guy.TEST3@aol.com",
        userRole:'USER',
        firstName:"Test3",
        surName:"Test3",
        phoneNumber:"054-2345-082",
        addresses:[{
                name:"Home",
                city:"Natanya",
                street:"Hail",
                houseNumber:"3",
                floorNumber:3,
                aptNumber:5
            }],
        cart:[{
            orders:["test"],
            totalSum:200
        }]
    },
    { 
        _id=5,
        emailAddress:"Guy.TEST4@aol.com",
        userRole:'USER',
        firstName:"Test4",
        surName:"Test4",
        phoneNumber:"054-1234-082",
        addresses:[{
                name:"Home",
                city:"Rehovot",
                street:"Hail",
                houseNumber:"3",
                floorNumber:3,
                aptNumber:4
            }],
        cart:[{
            orders:["test"],
            totalSum:100
        }]
    },  
    { 
        _id=6,
        emailAddress:"Guy.TEST5@aol.com",
        userRole:'USER',
        firstName:"Test5",
        surName:"Test5",
        phoneNumber:"054-7652-082",
        addresses:[{
                name:"Home",
                city:"Haifa",
                street:"Hail",
                houseNumber:"3",
                floorNumber:3,
                aptNumber:8
            }],
        cart:[{
            orders:["test"],
            totalSum:400
        }]
    },  
    { 
        _id=7,
        emailAddress:"Guy.TEST5@aol.com",
        userRole:'USER',
        firstName:"Test6",
        surName:"Test6",
        phoneNumber:"054-4567-082",
        addresses:[{
                name:"Home",
                city:"Nes-tziona",
                street:"Hail",
                houseNumber:"3",
                floorNumber:3,
                aptNumber:3
            }],
        cart:[{
            orders:["test"],
            totalSum:340
        }]
    },  
    { 
        _id=8,
        emailAddress:"Guy.TEST6@aol.com",
        userRole:'USER',
        firstName:"Test7",
        surName:"Test7",
        phoneNumber:"054-1233-082",
        addresses:[{
                name:"Home",
                city:"Bat-Yam",
                street:"Hail",
                houseNumber:"3",
                floorNumber:8,
                aptNumber:7
            }],
        cart:[{
            orders:["test"],
            totalSum:250
        }]
    },
    { 
        _id=9,
        emailAddress:"Guy.TEST7@aol.com",
        userRole:'USER',
        firstName:"Test8",
        surName:"Test8",
        phoneNumber:"054-9082-082",
        addresses:[{
                name:"Home",
                city:"Beer-sheba",
                street:"Hail",
                houseNumber:"3",
                floorNumber:9,
                aptNumber:10
            }],
        cart:[{
            orders:["test"],
            totalSum:270
        }]
    }, 
    { 
        _id=10,
        emailAddress:"Guy.TEST8@aol.com",
        userRole:'USER',
        firstName:"Test9",
        surName:"Test9",
        phoneNumber:"054-9485-082",
        addresses:[{
                name:"Home",
                city:"Tel-Aviv",
                street:"Hail",
                houseNumber:"3",
                floorNumber:2,
                aptNumber:1
            }],
        cart:[{
            orders:["test"],
            totalSum:230
        }]
    }


]