

######################## Target All ########################

### get all orders 
GET http://localHost:8080/api/orders HTTP/1.1

### add an order
POST http://localHost:8080/api/orders HTTP/1.1
content-type: application/json

{
    "userId":"6002fdbfaf469548f0bb42f3",
    "orderAddress":{
        "_id":"60252b3cb67369011c9aa77e",
        "name":"Home",
        "city":"Netaim",
        "street":"hail",
        "houseNumber":"2"
    },
    "orderFrequency":1,
    "isOrderActive":"false",
    "orderFlowerBouquetIds":[{
        "flowerBouquetId":"6005b4e5a293d135243beb1a",
        "bouquetAmount":1
    }],
    "orderTotalSum":119,
    "providerId":"-"
}

###################### Target Specific #####################

### get a specific order
GET http://localHost:8080/api/orders/5ffb3ef599e67425cca4dc99 HTTP/1.1

### change a specific order
PATCH http://localHost:8080/api/orders/5ffb3ef599e67425cca4dc99 HTTP/1.1
content-type: application/json

{
    "providerId": "5ffb559cd5000b13c432796a"
}

### delete a specific order
DELETE http://localHost:8080/api/orders/5ffb3ef599e67425cca4dc99 HTTP/1.1

### getTotal
GET http://localHost:8080/api/orders/getTotal HTTP/1.1