

######################## Target All ########################

### get all orders 
GET http://localHost:8080/api/orders HTTP/1.1

### add an order
POST http://localHost:8080/api/orders HTTP/1.1
content-type: application/json

{
    "userId": "5ffb3060cb30cb4e641f9ead", 
    "orderAddress": {
        "_id": "5ffb3060cb30cb4e641f9eae",
        "name": "Home",
        "city": "testavile",
        "street": "testastreet",
        "houseNumber": "4/5",
        "floorNumber": 7,
        "aptNumber": 7
    }, 
    "orderFrequency": 2, 
    "isOrderActive": "false", 
    "orderFlowerBouquetIds": [{
        "flowerBouquetId": "5ffaf9f2df5ea438e4e183be",
        "bouquetAmount": 3
    }]
}

###################### Target Specific #####################

### get a specific order
GET http://localHost:8080/api/orders/5ffb3ef599e67425cca4dc99 HTTP/1.1

### change a specific order
PATCH http://localHost:8080/api/orders/5ffb3ef599e67425cca4dc99 HTTP/1.1
content-type: application/json

{
    "providerId": "5ffb559cd5000b13c432796a"
}

### delete a specific order
DELETE http://localHost:8080/api/orders/5ffb3ef599e67425cca4dc99 HTTP/1.1

### getTotal
GET http://localHost:8080/api/orders/getTotal HTTP/1.1